import Link from "next/link";
import { getLatestMealPlan, listMembers } from "@/lib/db";
import GeneratePlan from "@/components/GeneratePlan";
import type { Member } from "@/lib/types";

export const dynamic = "force-dynamic";

const SLOT_ORDER = ["breakfast", "lunch", "dinner", "snack"];
const SLOT_ICON: Record<string, string> = {
  breakfast: "☀️",
  lunch: "🥗",
  dinner: "🍲",
  snack: "🍎",
};
const CATEGORY_COLOR: Record<string, string> = {
  veggies: "bg-herb-100 text-herb-700",
  fruits: "bg-rose-100 text-rose-700",
  protein: "bg-orange-100 text-orange-700",
  grains: "bg-amber-100 text-amber-700",
  treats: "bg-purple-100 text-purple-700",
};

export default function MealPlanPage() {
  const plan = getLatestMealPlan();
  const members = listMembers();
  const nameById = new Map<string, string>(members.map((m: Member) => [m.id, m.name]));
  const hasKey = !!process.env.OPENROUTER_API_KEY;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold text-stone-900">Meal plan</h1>
        {plan && (
          <Link href="/grocery" className="btn-ghost">
            🛒 View grocery list
          </Link>
        )}
      </div>

      <GeneratePlan hasKey={hasKey} />

      {!plan && (
        <p className="text-stone-600">No meal plan yet — generate your first one above.</p>
      )}

      {plan && (
        <div className="space-y-6">
          <div className="card bg-herb-50/60 p-4">
            <p className="text-sm text-stone-700">
              <span className="font-medium">Week of {plan.weekStart}.</span> {plan.familyNotes}
            </p>
            <p className="mt-1 text-xs text-stone-400">Generated by {plan.model}</p>
          </div>

          <div className="space-y-5">
            {plan.days.map((day) => (
              <section key={day.day}>
                <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-stone-500">
                  {day.day} · {day.date}
                </h2>
                <div className="grid gap-3">
                  {[...day.meals]
                    .sort((a, b) => SLOT_ORDER.indexOf(a.slot) - SLOT_ORDER.indexOf(b.slot))
                    .map((meal, i) => (
                      <div key={i} className="card p-4">
                        <div className="flex flex-wrap items-start justify-between gap-2">
                          <div>
                            <div className="flex items-center gap-2">
                              <span>{SLOT_ICON[meal.slot] ?? "🍽️"}</span>
                              <span className="font-medium text-stone-900">{meal.title}</span>
                              {meal.cuisine && (
                                <span className="chip bg-stone-100 text-stone-500">
                                  {meal.cuisine}
                                </span>
                              )}
                            </div>
                            <p className="mt-1 text-sm text-stone-600">{meal.description}</p>
                          </div>
                          {meal.prepMinutes > 0 && (
                            <span className="chip bg-stone-100 text-stone-500">
                              ⏱ {meal.prepMinutes}m
                            </span>
                          )}
                        </div>

                        <div className="mt-2 flex flex-wrap gap-1.5">
                          {meal.categories.map((c) => (
                            <span key={c} className={`chip ${CATEGORY_COLOR[c] ?? "bg-stone-100"}`}>
                              {c}
                            </span>
                          ))}
                          {meal.tags.slice(0, 4).map((t) => (
                            <span key={t} className="chip bg-stone-50 text-stone-500">
                              {t}
                            </span>
                          ))}
                        </div>

                        {meal.healthNotes && (
                          <p className="mt-2 rounded-lg bg-herb-50 p-2 text-xs text-herb-700">
                            💡 {meal.healthNotes}
                          </p>
                        )}

                        <p className="mt-2 text-xs text-stone-400">
                          For: {meal.forMembers.map((id) => nameById.get(id) ?? id).join(", ")}
                        </p>
                      </div>
                    ))}
                </div>
              </section>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
