import Link from "next/link";
import { getChildMembers, getLatestToddlerPlan, getMarksForPlan } from "@/lib/db";
import GenerateToddlerPlan from "@/components/GenerateToddlerPlan";
import ActivityCard from "@/components/ActivityCard";

export const dynamic = "force-dynamic";

export default function ToddlerPage() {
  const children = getChildMembers();
  const child = children[0];
  const hasKey = !!process.env.OPENROUTER_API_KEY;

  if (!child) {
    return (
      <div className="space-y-4">
        <h1 className="text-2xl font-semibold text-stone-900">Toddler Time</h1>
        <div className="card p-6 text-center">
          <p className="text-stone-600">
            No child in the family yet. Add one on the{" "}
            <Link href="/family" className="font-medium text-herb-700 underline">
              Family page
            </Link>{" "}
            to start planning play.
          </p>
        </div>
      </div>
    );
  }

  const plan = getLatestToddlerPlan(child.id);
  const marks = plan ? getMarksForPlan(plan.id) : new Map();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-stone-900">Toddler Time</h1>
        <p className="text-sm text-stone-500">
          Play, learning &amp; weekend adventures for {child.name} · age {child.ageYears ?? 3}
        </p>
      </div>

      <GenerateToddlerPlan hasKey={hasKey} childName={child.name} />

      {!plan && (
        <p className="text-stone-600">No plan yet — generate {child.name}&apos;s first week above.</p>
      )}

      {plan && (
        <div className="space-y-6">
          <div className="card bg-herb-50/60 p-4">
            {plan.theme && (
              <p className="text-sm font-semibold text-herb-800">🧸 {plan.theme}</p>
            )}
            <p className="mt-1 text-sm text-stone-700">
              <span className="font-medium">Week of {plan.weekStart}.</span> {plan.overview}
            </p>
            {plan.summerTips.length > 0 && (
              <div className="mt-3 rounded-lg bg-amber-50 p-3">
                <p className="text-xs font-semibold uppercase tracking-wide text-amber-700">
                  ☀️ {plan.season} safety
                </p>
                <ul className="mt-1 list-disc space-y-0.5 pl-4 text-xs text-amber-800">
                  {plan.summerTips.map((t, i) => (
                    <li key={i}>{t}</li>
                  ))}
                </ul>
              </div>
            )}
            <p className="mt-2 text-xs text-stone-400">Generated by {plan.model}</p>
          </div>

          <div className="space-y-5">
            {plan.days.map((day) => (
              <section key={day.day}>
                <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-stone-500">
                  {day.day} · {day.date}
                </h2>
                <div className="grid gap-3">
                  {day.activities.length === 0 ? (
                    <p className="text-sm text-stone-400">No activities for this day.</p>
                  ) : (
                    day.activities.map((a) => (
                      <ActivityCard
                        key={a.id}
                        activity={a}
                        planId={plan.id}
                        mark={marks.get(a.id)}
                      />
                    ))
                  )}
                </div>
              </section>
            ))}
          </div>

          {plan.weekendIdeas.length > 0 && (
            <section>
              <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-stone-500">
                🌳 Weekend adventures
              </h2>
              <div className="grid gap-3">
                {plan.weekendIdeas.map((a) => (
                  <ActivityCard
                    key={a.id}
                    activity={a}
                    planId={plan.id}
                    mark={marks.get(a.id)}
                  />
                ))}
              </div>
            </section>
          )}
        </div>
      )}
    </div>
  );
}
